version: "2"

run:
  timeout: 5m
  tests: false

output:
  sort-order:
    - linter
    - severity
    - file

linters:
  exclusions:
    paths:
      - ".*mock\\.go$"
      - ".*test\\.go$"
  enable:
    - unparam
    - unused
    - unconvert
    - misspell
    - errcheck
    - contextcheck
    - ineffassign
    - staticcheck
    - bodyclose
    - dupl
    - errorlint
    - funlen
    - govet
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - prealloc
    - revive
    - staticcheck
    - whitespace
    - nestif
    - godot
    - gosmopolitan
  settings:
    # https://golangci-lint.run/usage/linters/#linters-configuration
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    nestif:
      min-complexity: 15
    funlen:
      lines: 100
      ignore-comments: true

formatters:
  exclusions:
    paths:
      - ".*mock\\.go$"
      - ".*test\\.go$"
  enable:
    - gofmt
    - goimports
