run:
  timeout: 5m
  tests: false
  skip-dirs-use-default: true
  skip-files:
    - ".*mock\\.go$"
    - ".*test\\.go$"

output:
  sort-results: true
  print-linter-name: true

linters:
  fast: false
  disable:
    - typecheck
  enable:
    - unparam
    - unused
    - unconvert
    - misspell
    - errcheck
    - contextcheck
    - ineffassign
    - staticcheck
    - bodyclose
    - dupl
    - errorlint
    - funlen
    - gofmt
    - goimports
    - gosimple
    - govet
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - prealloc
    - revive
    - stylecheck
    - whitespace
    - nestif
    - godot
    - gosmopolitan

linters-settings:
  # https://golangci-lint.run/usage/linters/#linters-configuration
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  nestif:
    min-complexity: 15
  funlen:
    lines: 100
    ignore-comments: true

