apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: member-lib
  title: "Member Lib"
  description: "Member & Partner Team's Go: Crafted abstract packages for various use cases to enhance productivity and eliminate redundancy."
  tags:
    - "go"
    - "pkg"
  annotations:
    github.com/project-slug: coopnorge/member-lib
    backstage.io/techdocs-ref: dir:.
spec:
  profile:
    displayName: "Member Lib"
  type: library
  lifecycle: production
  owner: member
  dependsOn:
    - component:github-workflow-techdocs
    - component:techdocs
    - component:vale-coop
