version: "3.7"

services:
  golang-devtools:
    build:
      context: devtools
      target: golang-devtools
      dockerfile: Dockerfile
    privileged: true
    command: validate VERBOSE=all
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - .:/srv/workspace:z
      - ${DOCKER_CONFIG:-~/.docker}:/root/.docker
      - ${GIT_CONFIG:-~/.gitconfig}:${GIT_CONFIG_GUEST:-/root/.gitconfig}
      - ${SSH_CONFIG:-~/.ssh}:/root/.ssh
      - ${XDG_CACHE_HOME:-xdg-cache-home}:/root/.cache
    environment:
      GOMODCACHE: /root/.cache/go-mod

  techdocs:
    build:
      context: devtools
      dockerfile: Dockerfile
      target: techdocs
    working_dir: /srv/workspace
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-}
      GCLOUD_PROJECT: ${GCLOUD_PROJECT:-}
    volumes:
      - .:/srv/workspace:z
      - ${XDG_CACHE_HOME:-xdg-cache-home}:/root/.cache
      - $HOME/.config/gcloud:/root/.config/gcloud
      - ${GOOGLE_APPLICATION_CREDENTIALS:-nothing}:${GOOGLE_APPLICATION_CREDENTIALS:-/tmp/empty-GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - "127.0.0.1:3000:3000/tcp"
      - "127.0.0.1:8000:8000/tcp"
    command: serve

volumes:
  xdg-cache-home: { }
  devtools-var: {}
  nothing: { }
