version: "3.7"

services:
  golang-devtools:
    build:
      context: docker-compose
      target: golang-devtools
      dockerfile: Dockerfile
    privileged: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - .:/srv/workspace:z
      - ${DOCKER_CONFIG:-~/.docker}:/root/.docker
      - ${GIT_CONFIG:-~/.gitconfig}:${GIT_CONFIG_GUEST:-/root/.gitconfig}
      - ${SSH_CONFIG:-~/.ssh}:/root/.ssh
      - ${XDG_CACHE_HOME:-xdg-cache-home}:/root/.cache
    environment:
      GOMODCACHE: /root/.cache/go-mod

volumes:
  xdg-cache-home: { }
  nothing: { }
