name: Codespell
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  codespell:
    name: "Check for spelling errors"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: codespell-project/actions-codespell@3b7da264292a727fcdc4acdc9eaf9a5abb92ba10 # master
        with:
          check_filenames: true
          skip: "./vendor,./telemetry,go.mod,go.sum"
  build:
    needs:
      - "codespell"
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        name: "Catch errors"
        if: |
          needs.codespell.result == 'failure'
    permissions: {}
